### ISSUE TITLE
All first screen and some other sections link to external CDNs

### ISSUE THREAD

**Issue by tooevangelist** [ProtocolONE/ptah-editor#427]
**Describe the bug**
All first screen and some other sections link to external CDNs for background images and videos

```
const BG_SECTION = 'url(https://gn823.cdn.stg.gamenet.ru/0/8ifGM/o_7byuz.jpg)'
background-image': 'url("https://gn543.cdn.stg.gamenet.ru/0/8iMxM/o_18R5TC.svg")'
backgroundVideo: 'https://gn357.cdn.stg.gamenet.ru/0/8iNCR/o_1vLDJn.mp4'

```
**To Reproduce**
see https://github.com/ProtocolONE/ptah-editor/blob/develop/src/components/sections/first-screen/
Also reproducible with other elements, such as https://github.com/ProtocolONE/ptah-editor/blob/develop/src/components/sections/elements/FrequentlyAskedQuestions.vue

**Expected behavior**
Some links refer to the local files in the repo `cover: '/img/covers/first-screen-fantasy-video-back.jpg'`, what probably makes it easier for the user to modify the images and the theme overall.

**Comment by Temarie** [comment]
Спасибо за отчет,
